name: card_rec_env
channels:
  - defaults
dependencies:
  - python=3.9.16
  - pip:
    - algo-ops
    - ocr-ops
    - ezplotly
    - numpy
    - pandas
    - pokemontcgsdk
    - bidict
    - natsort
    - requests
    - black
    - twine
    - nose2